# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-helloworld',
                'doc_host': 'https://LotsOfOrg.github.io',
                'git_url': 'https://github.com/LotsOfOrg/nbdev-helloworld',
                'lib_path': 'nbdev_helloworld'},
  'syms': { 'nbdev_helloworld.core': {'nbdev_helloworld.core.foo': ('core.html#foo', 'nbdev_helloworld/core.py')},
            'nbdev_helloworld.hello': {'nbdev_helloworld.hello.say_hello': ('core.html#say_hello', 'nbdev_helloworld/hello.py')}}}
